###create tour
POST  http://localhost:4100/tour
Content-Type: application/json
{
    "destination": "Mt Elgon",
    "content": "image.com",
    "price": "450.00",
    "startDate": "04-20-2024",
    "endDate": "04-30-2024"
}

###

GET http://localhost:4100/tour
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZTgzM2ZlNy1kZjhjLTRiZWQtODdjOS0yOTIzNDA4NDk0NjMiLCJmaXJzdG5hbWUiOiJHYXZpbiIsImxhc3RuYW1lIjoiV29vZCIsImVtYWlsIjoid29vZEBob29saS5jb20iLCJpc0FkbWluIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJjb250ZW50IjoiaW1hZ2UuY29tIiwiaWF0IjoxNzA4ODY0MzMxLCJleHAiOjE3MDg4Njc5MzF9.0KDbpReR70q2Qsj1QgDHpq8SQur-ftLO94ShAOSSC1c