###Create User
POST http://localhost:4100/users
Content-Type: application/json

{
  "firstname": "Duncan",
  "lastname": "Kingangi",
  "email": "kingangiduncan47@gmail.com",
  "content": "https://happytravel.viajes/wp-content/uploads/2020/04/146-1468479_my-profile-icon-blank-profile-picture-circle-hd.png",
  "password": "duncan"
}

### Get Users
GET http://localhost:4100/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZTgzM2ZlNy1kZjhjLTRiZWQtODdjOS0yOTIzNDA4NDk0NjMiLCJmaXJzdG5hbWUiOiJHYXZpbiIsImxhc3RuYW1lIjoiV29vZCIsImVtYWlsIjoid29vZEBob29saS5jb20iLCJpc0FkbWluIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJjb250ZW50IjoiaW1hZ2UuY29tIiwiaWF0IjoxNzA5MTkxNzY2LCJleHAiOjE3NDUxOTE3NjZ9.1r0agyAwe-4jJUhIx80mK652Lnwua9Ab0RVi-dHHtHQ

### Update User
PUT http://localhost:4100/users/update/uniqueUserId
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

{
  "firstname": "UpdatedFirstName",
  "lastname": "UpdatedLastName",
  "email": "updated.email@example.com",
  "isAdmin": true
}

### Get One User
GET http://localhost:4100/users/uniqueUserId
Authorization: Bearer YOUR_ACCESS_TOKEN

### Delete User
DELETE http://localhost:4100/users/delete/uniqueUserId
Authorization: Bearer YOUR_ACCESS_TOKEN
